version: '3.7'
services:
  db:
    container_name: tree-academy_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    image: postgres:14.3
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    networks:
      - tree-academy_network

  pgadmin:
    container_name: tree-academy_pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    image: dpage/pgadmin4:6.15
    ports:
      - ${PGADMIN_PORT}:80
    restart: always
    volumes:
      - ./tmp/pgadmin:/var/lib/pgadmin
    networks:
      - tree-academy_network

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: tree-academy_api
  #   depends_on:
  #     - db
  #   ports:
  #     - ${PORT}:4000
  #   restart: always
  #   networks:
  #     - tree-academy_network

networks:
  tree-academy_network:
    driver: bridge
